name: colabseg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pyqt
  - pip:
    - magicgui
    - napari
    - h5py
    - pyntcloud
    - addict==2.4.0
    - appnope==0.1.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - certifi==2023.11.17
    - cffi==1.15.0
    - charset-normalizer==3.3.2
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docopt==0.6.2
    - entrypoints==0.4
    - executing==0.8.3
    - fonttools==4.31.2
    - future==0.18.2
    - idna==3.6
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - ipykernel==6.9.2
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.0
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mrcfile==1.4.3
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - notebook==6.4.10
    - numpy==1.22.3
    - open3d==0.14.1
    - packaging==21.3
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pipreqs==0.4.13
    - pluggy==1.0.0
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - py3dmol==2.0.1.post1
    - pycparser==2.21
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pytest==7.1.2
    - pyzmq==22.3.0
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - requests==2.31.0
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - send2trash==1.8.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - terminado==0.13.3
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - tornado==6.1
    - tqdm==4.63.0
    - traitlets==5.1.1
    - urllib3==2.1.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - yarg==0.1.9
    - zipp==3.7.0
