# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Test with pytest
      run: |
        pytest


  docs:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docs
        run: |
          python -mpip install .
          python -mpip install Sphinx pydata-sphinx-theme sphinx_design numpydoc sphinx_copybutton
          cd doc
          make clean
          make html
          mkdir -p ../public
          mv _build/html/* ../public/

      - name: Upload Public as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public


  pages:
    runs-on: ubuntu-latest
    needs: docs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Public Artifacts
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public

      - name: List directory after downloading artifact
        run: |
          ls -al
          ls -al ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
